### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by tandatit** [context-labs/babyagi-ts#3]
i got error message when init agent:

```
ReferenceError: Headers is not defined
    at createRequest (file:///Users/tidusvn05/.nvm/versions/node/v16.16.0/lib/node_modules/babyagi/node_modules/langchain/dist/util/axios-fetch-adapter.js:234:21)
    at fetchAdapter (file:///Users/tidusvn05/.nvm/versions/node/v16.16.0/lib/node_modules/babyagi/node_modules/langchain/dist/util/axios-fetch-adapter.js:164:21)
    at dispatchRequest (/Users/tidusvn05/.nvm/versions/node/v16.16.0/lib/node_modules/babyagi/node_modules/axios/lib/core/dispatchRequest.js:58:10)
```
anyone help me for this,  thanks

**Comment by ai-slave** [comment]
Running into same error. 
Installed node-fetch, and added imports for Headers & Request, but now I'm gettting 

```Error: Network Error```
